### ISSUE TITLE
References

### ISSUE THREAD

**Issue by sergey-melnychuk** [sergey-melnychuk/sergey-melnychuk.github.io#43]
Please post your feedback and/or references as comments on this issue. Thank you!

**Comment by Mirko-von-Leipzig** [comment]
I am Mirko von Leipzig, and I was Sergey's team lead on the [Pathfinder](https://github.com/eqlabs/pathfinder) project, a full node for the Starknet blockchain. The project was contracted by Starkware and the Starknet foundation, and is considered part of the core infrastructure of Starknet. The project is multifaceted and incorporates many parts of distributed systems engineering.

Sergey joined our tightnit team and quickly made himself at home there, and within the codebase. During his time with us he displayed proficiency across a wide array of skills; databases, RPC, schemas, networking, conccurency and cloud infrastructure as some examples. He had several major contributions, in particular to our observiability, infrastructure, configuration and RPC implementations.

Socially, Sergey fit right in. His manner is straight-forward and direct, and he adjusted to the code and organisational style of the project very quickly. He was also worth a few laughs 🙂
